# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY . /app

# Upgrade pip and install uv and project dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir uv \
    && pip install --no-cache-dir -e .

# Expose a port if necessary (not strictly needed for stdio MCP servers)

# Run the server using uv as per instructions
CMD ["uv", "run", "fastn-server.py", "--api_key", "dummy_api_key", "--space_id", "dummy_space_id"]
